### ISSUE TITLE
Credentials removal

### ISSUE THREAD

**Issue by guimou** [ksingh7/openshift-photo-album-app#1]
https://github.com/ksingh7/openshift-photo-album-app/blob/e94a9b6d22e77be1bbd395cbd2afaa69f8087631/Dockerfile#L13

I suppose those are the credentials from your test environment, but you should consider deleting them, just in case...

**Comment by ksingh7** [comment]
I remember i intentionally re-generated those, but yes it MUST NOT BE THERE Thanks @guimou
